package com.fubang.fubangzhibo.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ROOM_LIST_ENTITY".
 */
public class RoomListEntity {

    private Long id;
    private String roomid;
    private String roomname;
    private String roompic;
    private String roomrs;
    private String roompwd;
    private String rscount;
    private String gateway;

    public RoomListEntity() {
    }

    public RoomListEntity(Long id) {
        this.id = id;
    }

    public RoomListEntity(Long id, String roomid, String roomname, String roompic, String roomrs, String roompwd, String rscount, String gateway) {
        this.id = id;
        this.roomid = roomid;
        this.roomname = roomname;
        this.roompic = roompic;
        this.roomrs = roomrs;
        this.roompwd = roompwd;
        this.rscount = rscount;
        this.gateway = gateway;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getRoomid() {
        return roomid;
    }

    public void setRoomid(String roomid) {
        this.roomid = roomid;
    }

    public String getRoomname() {
        return roomname;
    }

    public void setRoomname(String roomname) {
        this.roomname = roomname;
    }

    public String getRoompic() {
        return roompic;
    }

    public void setRoompic(String roompic) {
        this.roompic = roompic;
    }

    public String getRoomrs() {
        return roomrs;
    }

    public void setRoomrs(String roomrs) {
        this.roomrs = roomrs;
    }

    public String getRoompwd() {
        return roompwd;
    }

    public void setRoompwd(String roompwd) {
        this.roompwd = roompwd;
    }

    public String getRscount() {
        return rscount;
    }

    public void setRscount(String rscount) {
        this.rscount = rscount;
    }

    public String getGateway() {
        return gateway;
    }

    public void setGateway(String gateway) {
        this.gateway = gateway;
    }

}
